Repository AY1920S2-CS2103T-W17-1/main, pull requests merged in 2020-03, with the labels that each got.

#70 Initial Deck implementation
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/View.java
  src/main/java/seedu/address/logic/commands/cardcommands/AddCardCommand.java
  src/main/java/seedu/address/logic/commands/cardcommands/DeleteCardCommand.java
  src/main/java/seedu/address/logic/parser/AddCardCommandParser.java
  src/main/java/seedu/address/logic/parser/CreateCardCommandParser.java
  src/main/java/seedu/address/logic/parser/DeckParser.java
  src/main/java/seedu/address/logic/parser/DeleteCardCommandParser.java
  src/main/java/seedu/address/logic/parser/LibraryParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/model/deck/card/Card.java
  src/main/java/seedu/address/model/deck/card/UniqueCardList.java
  src/main/java/seedu/address/model/deck/exceptions/CardNotFoundException.java
  src/main/java/seedu/address/model/deck/exceptions/DuplicateCardException.java
  src/main/java/seedu/address/storage/JsonAdaptedDeck.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/java/seedu/address/logic/parser/LibraryParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedDeckTest.java
Labels: status.Ongoing

#86 Add initial Edit card functionality
  src/main/java/seedu/address/logic/commands/cardcommands/AddCardCommand.java
  src/main/java/seedu/address/logic/commands/cardcommands/DeleteCardCommand.java
  src/main/java/seedu/address/logic/commands/cardcommands/EditCardCommand.java
  src/main/java/seedu/address/logic/parser/AddCardCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteCardCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCardCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/model/deck/card/UniqueCardList.java
Labels: type.Task

#113 Fix delete card function
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/commands/cardcommands/DeleteCardCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/deck/Deck.java
  src/main/java/seedu/address/model/deck/card/UniqueCardList.java
Labels: severity.High

#115 Fix edit card function
  src/main/java/seedu/address/logic/commands/cardcommands/EditCardCommand.java
  src/main/java/seedu/address/model/ModelManager.java
Labels: severity.High

#154 Update DG
  docs/DeveloperGuide.adoc
Labels: priority.High

#162 Update Storage diagram in DG
  docs/DeveloperGuide.adoc
  docs/diagrams/ArchitectureDiagram.png
  docs/diagrams/ArchitectureSequenceDiagram.png
  docs/diagrams/BetterModelClassDiagram.png
  docs/diagrams/CommitActivityDiagram.png
  docs/diagrams/DeleteSequenceDiagram.png
  docs/diagrams/EditSequenceDiagram.png
  docs/diagrams/LogicClassDiagram.png
  docs/diagrams/ModelClassDiagram.png
  docs/diagrams/StorageClassDiagram.png
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.png
  docs/diagrams/UndoRedoState0.png
  docs/diagrams/UndoRedoState1.png
  docs/diagrams/UndoRedoState2.png
  docs/diagrams/UndoRedoState3.png
  docs/diagrams/UndoRedoState4.png
  docs/diagrams/UndoRedoState5.png
  docs/diagrams/UndoSequenceDiagram.png
  docs/diagrams/plantuml/AbeforeC.png
  docs/diagrams/plantuml/AllDown.png
  docs/diagrams/plantuml/ArrowLength.png
  docs/diagrams/plantuml/CbeforeA.png
  docs/diagrams/plantuml/HiddenArrows.png
  docs/diagrams/plantuml/PackagesAndConsistency.png
  docs/diagrams/plantuml/UpAndDown.png
Labels: status.Ongoing

#170 Change UG writing style
  docs/UserGuide.adoc
Labels: type.Chore

#177 Add statistics
  src/main/java/seedu/address/model/GameManager.java
  src/main/java/seedu/address/model/Statistics.java
Labels: priority.High
